# Font
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size        11.0

# Cursor
cursor_shape block
cursor_blink_interval 0

# Performance / Wayland
enable_audio_bell no
remember_window_size yes
initial_window_width  1000
initial_window_height 650

# Colors (neutre, s’intègre bien à ton thème)
background #1e1e2e
foreground #cdd6f4

# Padding
window_padding_width 8
