#################
### VARIABLES ###
#################

# Core modifiers
$mainMod = SUPER

# Apps
$terminal = kitty
$browser = firefox
$fileManager = nautilus

# Paths
$screenshotDir = $HOME/Images/Screenshots

# Launcher
$launcherTheme = ~/.config/rofi/spotlight.rasi
$launcherCmd = rofi -show drun -show-icons -hover-select -click-to-exit -theme $launcherTheme
