#################
### VARIABLES ###
#################

# Core modifiers
$mainMod = SUPER

# Apps
$terminal = kitty
$browser = firefox
$fileManager = nautilus

# Paths
$screenshotDir = $HOME/Images/Screenshots
$focusModeScript = $HOME/.config/bin/hypr-focus-mode.sh
$autoModePid = ${XDG_RUNTIME_DIR:-/tmp}/hypr-visual-mode.pid
$smartLayoutScript = $HOME/.config/bin/hypr-smart-layout.sh
$appRouterScript = $HOME/.config/bin/hypr-app-router.sh

# Launcher
$launcherTheme = ~/.config/rofi/spotlight.rasi
$launcherCmd = rofi -show drun -show-icons -hover-select -click-to-exit -theme $launcherTheme
