################
### MONITORS ###
################

# Ordre physique (gauche -> droite): DP-4, HDMI-A-1, eDP-1, DP-2
# DP-4 est tout a gauche
monitor = DP-4,1920x1200@59.95,0x0,1

# Dell P2416D
monitor = HDMI-A-1,1920x1080@60,1920x0,1

# Ecran laptop
monitor = eDP-1,1920x1200@144,3840x0,1

# DP-2 est tout a droite
monitor = DP-2,1920x1080@120,5760x0,1
