#############
### INPUT ###
#############
input {
    kb_layout = fr
    kb_variant = azerty
    kb_model = pc105
    follow_mouse = 1
    sensitivity = 0

    touchpad {
        natural_scroll = false
    }
}
