#############
### INPUT ###
#############
input {
    kb_layout = fr
    kb_variant = azerty
    kb_model = pc105
    repeat_delay = 280
    repeat_rate = 50
    follow_mouse = 1
    sensitivity = 0
    accel_profile = flat

    touchpad {
        natural_scroll = false
        tap-to-click = true
        drag_lock = true
        disable_while_typing = true
    }
}
