###################
### WINDOW RULES ###
###################

# Dialogues de fichiers
windowrule = match:title Open File, float on, center on, size 1100 750
windowrule = match:title Save File, float on, center on, size 1100 750
windowrule = match:title File Upload, float on, center on, size 1100 750
windowrule = match:title Ouvrir, float on, center on, size 1100 750
windowrule = match:title Enregistrer sous, float on, center on, size 1100 750
windowrule = match:title Picture-in-Picture, float on, pin on, size 480 270

# Outils systeme
windowrule = match:class pavucontrol, float on, center on
windowrule = match:class nm-connection-editor, float on, center on
windowrule = match:class blueman-manager, float on, center on
windowrule = match:class code-oss, opacity 0.92 0.85
windowrule = match:class qalculate-gtk, float on, center on, size 900 620

# Workspaces ergonomiques par application
windowrule = match:class firefox, workspace 2
windowrule = match:class code-oss, workspace 3
windowrule = match:class Code, workspace 3
windowrule = match:class discord, workspace 4
windowrule = match:class vesktop, workspace 4
windowrule = match:class Slack, workspace 4
windowrule = match:class spotify, workspace 5
windowrule = match:class org.telegram.desktop, workspace 6
windowrule = match:class TelegramDesktop, workspace 6
windowrule = match:class thunar, workspace 7
windowrule = match:class nautilus, workspace 7
