#!/usr/bin/env bash
title=$(playerctl metadata --format '{{artist}} - {{title}}' 2>/dev/null)
if [ -z "$title" ]; then
  echo "⏸︎"
else
  status=$(playerctl status 2>/dev/null)
  if [ "$status" = "Playing" ]; then
    echo "▶︎  $title"
  else
    echo "⏸︎  $title"
  fi
fi
