wallpaper {
    monitor = eDP-1
    path = /home/adeline/Pictures/wallpapers/catwoman.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/adeline/Pictures/wallpapers/catwoman.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/adeline/Pictures/wallpapers/catwoman.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-4
    path = /home/adeline/Pictures/wallpapers/catwoman.jpg
    fit_mode = cover
}

